export const random = [
  {
    _id: '5f64a092cc47fbc916756e2d',
    index: 0,
    guid: '97641667-8645-48ac-9250-e933aaa0a597',
    isActive: false,
    balance: '$2,413.84',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'brown',
    name: {
      first: 'Keith',
      last: 'Graham',
    },
    company: 'VIASIA',
    email: 'keith.graham@viasia.biz',
    phone: '+1 (847) 495-2578',
    address: '967 Withers Street, Idledale, Vermont, 1263',
    about:
      'Nostrud adipisicing duis voluptate tempor cillum quis incididunt cupidatat consectetur ea nulla ipsum proident Lorem. Qui excepteur est magna mollit qui labore. Fugiat nisi officia do veniam commodo pariatur dolore amet cillum amet eu. Lorem dolore Lorem enim culpa do ex.',
    registered: 'Friday, March 8, 2019 6:11 AM',
    latitude: '38.871863',
    longitude: '-176.372858',
    tags: ['adipisicing', 'veniam', 'ullamco', 'irure', 'qui'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Sharlene Wheeler',
      },
      {
        id: 1,
        name: 'Barlow Good',
      },
      {
        id: 2,
        name: 'Cherie Mathis',
      },
    ],
    greeting: 'Hello, Keith! You have 8 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f64a0925c9f1c87c7b17a1f',
    index: 1,
    guid: 'dbf89c66-e39e-4f8c-a95d-398050901fc8',
    isActive: true,
    balance: '$3,496.31',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'brown',
    name: {
      first: 'Marsha',
      last: 'Patterson',
    },
    company: 'LUDAK',
    email: 'marsha.patterson@ludak.me',
    phone: '+1 (994) 457-2907',
    address: '862 Locust Street, Virgie, Louisiana, 4803',
    about:
      'Eu ex quis ad fugiat qui id ea cupidatat anim. Reprehenderit occaecat et fugiat anim Lorem nulla. Dolore cupidatat esse consequat ad id duis veniam non nostrud ipsum. Velit consequat officia id cupidatat. Ut dolor cupidatat nostrud anim eiusmod. Quis ut in consequat deserunt. Quis fugiat incididunt proident qui fugiat mollit ut eiusmod commodo excepteur.',
    registered: 'Thursday, October 22, 2015 2:00 AM',
    latitude: '-10.846841',
    longitude: '-68.31278',
    tags: ['ullamco', 'amet', 'Lorem', 'consequat', 'magna'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Terrell Carney',
      },
      {
        id: 1,
        name: 'Sheila Mccall',
      },
      {
        id: 2,
        name: 'Barry Foreman',
      },
    ],
    greeting: 'Hello, Marsha! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5f64a0926876914378457e7a',
    index: 2,
    guid: 'bb7b0d3c-72a0-40dc-9479-baec5d2152a8',
    isActive: false,
    balance: '$2,520.80',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'blue',
    name: {
      first: 'Alberta',
      last: 'Bentley',
    },
    company: 'BOILCAT',
    email: 'alberta.bentley@boilcat.tv',
    phone: '+1 (842) 594-3714',
    address: '117 Cherry Street, Bawcomville, Texas, 7282',
    about:
      'Do sit veniam ea dolore. Fugiat proident ea sit laboris consectetur. Est id adipisicing veniam nulla ad do duis duis ullamco ad adipisicing magna non. Aliqua dolore est occaecat officia velit cupidatat non qui adipisicing ea sunt.',
    registered: 'Saturday, July 9, 2016 1:33 PM',
    latitude: '-37.230093',
    longitude: '-141.805145',
    tags: ['aliquip', 'magna', 'consectetur', 'irure', 'quis'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Perry Britt',
      },
      {
        id: 1,
        name: 'Petty Bradford',
      },
      {
        id: 2,
        name: 'Bentley Jensen',
      },
    ],
    greeting: 'Hello, Alberta! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f64a0929ef0adc0b640f446',
    index: 3,
    guid: '0ccaa672-6346-4d5c-aa10-99a543c0c42c',
    isActive: true,
    balance: '$1,195.57',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'green',
    name: {
      first: 'Benita',
      last: 'Dale',
    },
    company: 'EXTRAGENE',
    email: 'benita.dale@extragene.co.uk',
    phone: '+1 (802) 443-2282',
    address: '321 Tampa Court, Walland, Washington, 8633',
    about:
      'Excepteur duis voluptate non reprehenderit excepteur consequat est pariatur consequat ea excepteur ad id anim. Culpa id ex incididunt occaecat minim minim. Esse excepteur ad aute consectetur minim officia amet veniam nostrud deserunt. Reprehenderit ad labore voluptate aliqua Lorem ad ullamco minim. Tempor sint mollit anim ipsum voluptate cillum quis eu culpa et et reprehenderit elit elit. Lorem elit magna voluptate ut fugiat reprehenderit ut excepteur excepteur velit.',
    registered: 'Wednesday, December 25, 2019 4:36 PM',
    latitude: '-60.60633',
    longitude: '-70.013894',
    tags: ['enim', 'proident', 'ut', 'aliquip', 'adipisicing'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Maxwell Chen',
      },
      {
        id: 1,
        name: 'Goff Valentine',
      },
      {
        id: 2,
        name: 'Crawford Madden',
      },
    ],
    greeting: 'Hello, Benita! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f64a092b1f2e1d1c36ad811',
    index: 4,
    guid: 'c2a1cd9d-6930-4349-b5e3-5894b7030900',
    isActive: false,
    balance: '$1,521.51',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'blue',
    name: {
      first: 'Miriam',
      last: 'Schmidt',
    },
    company: 'CEPRENE',
    email: 'miriam.schmidt@ceprene.info',
    phone: '+1 (806) 414-2956',
    address: '456 Hastings Street, Machias, Michigan, 5632',
    about:
      'Sit mollit ex laboris ea officia. Laborum velit anim amet reprehenderit veniam aute excepteur consectetur excepteur et. Nisi deserunt sit quis aute voluptate consequat sit laborum laborum. Ut adipisicing aliqua ut duis. Consectetur culpa cillum non culpa elit quis aute ipsum veniam. Nisi incididunt cupidatat nisi nostrud irure sint consequat non eiusmod esse do. Fugiat ad laboris sit sit do pariatur anim voluptate.',
    registered: 'Tuesday, November 17, 2015 9:57 AM',
    latitude: '-14.770703',
    longitude: '48.091471',
    tags: ['cillum', 'id', 'ex', 'dolore', 'ipsum'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Alexis Russell',
      },
      {
        id: 1,
        name: 'Savage Humphrey',
      },
      {
        id: 2,
        name: 'Chrystal Bass',
      },
    ],
    greeting: 'Hello, Miriam! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f64a0926976639fb3a1eb3a',
    index: 5,
    guid: 'e7e5580e-4812-4c8f-9a39-783b591db818',
    isActive: true,
    balance: '$3,689.14',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'green',
    name: {
      first: 'Romero',
      last: 'Perkins',
    },
    company: 'REALMO',
    email: 'romero.perkins@realmo.io',
    phone: '+1 (875) 502-3269',
    address: '268 Dinsmore Place, Chilton, New Jersey, 9614',
    about:
      'Anim occaecat laboris veniam voluptate ut nulla laboris ex proident amet sint velit. Ipsum eiusmod esse minim minim incididunt fugiat. Occaecat aliquip incididunt magna Lorem et fugiat veniam deserunt adipisicing ullamco. Culpa dolore nulla do labore excepteur commodo nulla est. Esse aute et tempor exercitation anim consectetur aliquip ex Lorem. Aliquip eu irure laborum ex.',
    registered: 'Wednesday, September 16, 2020 6:45 AM',
    latitude: '-50.570942',
    longitude: '87.425346',
    tags: ['amet', 'dolor', 'amet', 'Lorem', 'ad'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Cassie Browning',
      },
      {
        id: 1,
        name: 'Lloyd Curtis',
      },
      {
        id: 2,
        name: 'Frank Vazquez',
      },
    ],
    greeting: 'Hello, Romero! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f64a092d6d6308e01066ed7',
    index: 6,
    guid: 'c72fa486-f435-4355-b11f-557554442050',
    isActive: false,
    balance: '$1,825.42',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'green',
    name: {
      first: 'Hall',
      last: 'Williams',
    },
    company: 'ACCUFARM',
    email: 'hall.williams@accufarm.name',
    phone: '+1 (961) 532-3701',
    address: '996 Neptune Court, Loretto, Rhode Island, 4076',
    about:
      'Ullamco aute officia proident cillum do Lorem. Amet ea duis deserunt duis quis irure ad tempor culpa nulla consequat non enim ipsum. Laborum sunt ut pariatur et. Officia culpa do non consectetur sint aliqua aliquip qui esse fugiat excepteur laborum nisi ea. Anim est magna ullamco ipsum reprehenderit.',
    registered: 'Saturday, April 25, 2015 6:10 AM',
    latitude: '67.265883',
    longitude: '-153.488809',
    tags: ['in', 'fugiat', 'labore', 'est', 'est'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Rosario Kramer',
      },
      {
        id: 1,
        name: 'Lorraine Macdonald',
      },
      {
        id: 2,
        name: 'Duke Hamilton',
      },
    ],
    greeting: 'Hello, Hall! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f64a0929dd264365768e5eb',
    index: 7,
    guid: '0bfd2f63-83aa-480a-8e73-294dbef06e6f',
    isActive: true,
    balance: '$2,329.15',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: {
      first: 'Pruitt',
      last: 'Jefferson',
    },
    company: 'COMVOY',
    email: 'pruitt.jefferson@comvoy.ca',
    phone: '+1 (938) 593-2067',
    address: '356 Gerritsen Avenue, Neibert, Federated States Of Micronesia, 9740',
    about:
      'Commodo minim reprehenderit dolor ullamco excepteur ad incididunt culpa. Aliqua aliquip aute enim duis nulla enim eu est nostrud. In sint magna velit officia irure quis eu irure amet nostrud sit. Ex ad incididunt ut mollit quis amet minim commodo. Eiusmod duis magna nisi sit est eiusmod quis esse ullamco officia.',
    registered: 'Tuesday, September 8, 2015 12:24 AM',
    latitude: '61.102999',
    longitude: '-122.441869',
    tags: ['non', 'consectetur', 'cillum', 'consectetur', 'ut'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Blanchard Wiggins',
      },
      {
        id: 1,
        name: 'Maribel Fletcher',
      },
      {
        id: 2,
        name: 'Rosalyn Medina',
      },
    ],
    greeting: 'Hello, Pruitt! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
];
